# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 21:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 10, 21, 17, 11, 508332, tzinfo=utc)),
        ),
    ]
