# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 17:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0002_auto_20180610_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 10, 17, 12, 45, 393523, tzinfo=utc)),
        ),
    ]
