# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 20:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0002_auto_20180618_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minskill',
            name='name',
            field=models.CharField(blank=True, default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='availability',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 24, 20, 53, 49, 504025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timeZone',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, default='null', max_length=50),
        ),
    ]
