# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-13 21:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0004_auto_20180613_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minskill',
            name='profile',
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 13, 21, 3, 54, 856931, tzinfo=utc)),
        ),
    ]
