# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-13 21:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0005_auto_20180613_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 13, 21, 10, 54, 614482, tzinfo=utc)),
        ),
    ]
