# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 18:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0005_auto_20180610_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 10, 18, 12, 29, 935248, tzinfo=utc)),
        ),
    ]
