# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 00:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0007_auto_20180614_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='type',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 15, 0, 25, 2, 14260, tzinfo=utc)),
        ),
    ]
