# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 22:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0009_auto_20180615_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 15, 22, 44, 40, 524278, tzinfo=utc)),
        ),
    ]
