# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 22:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0011_auto_20180615_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 15, 22, 52, 50, 286922, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='skill',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skillSet', to='scrum.Profile'),
        ),
    ]
