# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-16 18:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0013_auto_20180616_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 16, 18, 49, 9, 275985, tzinfo=utc)),
        ),
    ]
