# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-18 01:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0017_auto_20180618_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 18, 1, 5, 46, 65322, tzinfo=utc)),
        ),
    ]
